### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use Python 3.4+ and the 'spawn' start method

### ISSUE THREAD

**Issue by 2a2a** [Feynman27/pytorch-detect-and-track#7]
Did I miss some configs? In readme file you said the project require python2.7.
The complete error is here:
`Traceback (most recent call last):
  File "trainval_net.py", line 342, in <module>
    data = next(vid_data_iter)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/pytorch-detect-to-track/lib/roi_data_layer/roibatchLoader.py", line 218, in __getitem__
    num_boxes.append(torch.LongTensor([min(gt_boxes[ientry].size(0), self.max_num_box)]).cuda())
  File "/root/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 384, in _lazy_new
    _lazy_init()
  File "/root/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 140, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use Python 3.4+ and the 'spawn' start method
`
Thank you.

**Comment by yhcao6** [comment]
Have you solved this problem?

**Comment by 2a2a** [comment]
> Have you solved this problem?

no, I used matlab version later

**Comment by ZongweiZhou1** [comment]
> Have you solved this problem?

[issue](https://discuss.pytorch.org/t/runtimeerror-cannot-re-initialize-cuda-in-forked-subprocess-to-use-cuda-with-multiprocessing-you-must-use-the-spawn-start-method/14083). 

The problem is due to multi-workers used in dataloader I think. And it's ok when `--nw=0`. But I dont know how to solve it to load data with muti-workers. 😢

**Comment by 2a2a** [comment]
> > Have you solved this problem?
> 
> [issue](https://discuss.pytorch.org/t/runtimeerror-cannot-re-initialize-cuda-in-forked-subprocess-to-use-cuda-with-multiprocessing-you-must-use-the-spawn-start-method/14083).
> 
> The problem is due to multi-workers used in dataloader I think. And it's ok when `--nw=0`. But I dont know how to solve it to load data with muti-workers. 😢

Thank you, it works
